server:
  port: 8080

spring:
  # 開発で必要があればここに追加設定

flyway:
  clean-disabled: false       # 開発ではクリーン許可

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    path: /swagger-ui
    operationsSorter: alpha
    tagsSorter: alpha
    tryItOutEnabled: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
    org.hibernate.SQL: DEBUG
  # org.hibernate.type.descriptor.sql: TRACE  # バインド値まで見る場合のみ一時的に
  pattern:
    level: "%5p [%X{rid}]"
