server:
  port: 8080
spring:
  application:
    name: minimal-app
logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: TRACE
  pattern:
    level: "%5p [%X{rid}]"
