-- items テーブル
CREATE TABLE IF NOT EXISTS items (
  id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,	-- 	自動採番
  public_id            VARCHAR(26)   NOT NULL,       -- ULID(26)
  billing_ym           VARCHAR(6)    NOT NULL,       -- yyyyMM
  usage_date           DATE          NOT NULL,
  title                VARCHAR(100)  NOT NULL,
  payer                VARCHAR(100)  NOT NULL,
  payment_method       VARCHAR(50)   NOT NULL,
  usage_amount         NUMERIC(10,2) NOT NULL,
  fee_amount           NUMERIC(10,2) NOT NULL,
  total_amount         NUMERIC(10,2) NOT NULL,
  current_month_paid   NUMERIC(10,2) NOT NULL,
  next_month_paid      NUMERIC(10,2) NOT NULL,
  is_new_item          BOOLEAN       NOT NULL DEFAULT false,
  category_id          BIGINT        NOT NULL,
  memo                TEXT,
  member_id            VARCHAR(26)   NOT NULL,
  created_at           TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  created_by           VARCHAR(26),
  updated_at           TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_by           VARCHAR(26),
  deleted_at           TIMESTAMPTZ,
  
  -- 形式チェック/金額チェック
  CONSTRAINT ck_items_billing_ym_format CHECK (billing_ym ~ '^[0-9]{6}$'),
  CONSTRAINT ck_items_ulid_len CHECK (char_length(public_id) = 26 AND char_length(member_id) = 26),
  CONSTRAINT ck_items_amounts_nonneg CHECK (
    usage_amount >= 0 AND fee_amount >= 0 AND total_amount >= 0
    AND current_month_paid >= 0 AND next_month_paid >= 0
  ),
  CONSTRAINT ck_items_total_amount CHECK (total_amount = usage_amount + fee_amount)
);

-- 論理削除前提の一意性（deleted_at IS NULL のみ対象）
CREATE UNIQUE INDEX IF NOT EXISTS uq_items_public_id_active
  ON items (public_id)
  WHERE deleted_at IS NULL;

-- 索引（member_id × billing_ym）
CREATE INDEX IF NOT EXISTS ix_items_member_id_billing_ym_active
  ON items (member_id, billing_ym)
  WHERE deleted_at IS NULL;

-- 外部キー（参照先のPKカラム名は実定義に合わせてください）
ALTER TABLE items
  ADD CONSTRAINT fk_items_category_id
  FOREIGN KEY (category_id) REFERENCES categories(pk);

ALTER TABLE items
  ADD CONSTRAINT fk_items_member_id
  FOREIGN KEY (member_id) REFERENCES members(id);

-- categories テーブル
CREATE TABLE IF NOT EXISTS categories (
	pk				BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
	id				INTEGER		NOT NULL,
	name			VARCHAR(20)	NOT NULL,
	upper_id		BIGINT,
	display_order	INTEGER		NOT NULL,
	member_id		VARCHAR(26)		NOT NULL,
	created_at   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
	created_by	 VARCHAR(26),
  	updated_at   TIMESTAMPTZ   NOT NULL DEFAULT CURRENT_TIMESTAMP,
  	updated_by	 VARCHAR(26),
  	deleted_at   TIMESTAMPTZ
);

-- 論理削除前提の一意制（deleted_at IS NULL のみ対象）: Partial Unique Index（PostgreSQL）
CREATE UNIQUE INDEX IF NOT EXISTS  uq_categories_id_member_id_active
  ON categories (id, member_id)
  WHERE deleted_at IS NULL;
  
-- 索引（member_id × display_order）
CREATE INDEX IF NOT EXISTS ix_categories_member_id_display_order_active
  ON categories (member_id, display_order)
  WHERE deleted_at IS NULL;

-- 外部キー（参照先のPKカラム名は実定義に合わせてください）
ALTER TABLE categories
  ADD CONSTRAINT fk_categories_upper_id
  FOREIGN KEY (upper_id) REFERENCES categories(pk);

ALTER TABLE categories
  ADD CONSTRAINT fk_categories_member_id
  FOREIGN KEY (member_id) REFERENCES members(id);

-- 形式・範囲チェック
ALTER TABLE categories
  ADD CONSTRAINT ck_categories_id_range CHECK (id BETWEEN 0 AND 9999),
  ADD CONSTRAINT ck_categories_display_order_range CHECK (display_order BETWEEN 0 AND 9999);
